name: bloc_suboptimal_mistake
description: Example project for my article

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.0.1
  freezed_annotation: 2.0.3

dev_dependencies:
  freezed: 2.0.3+1
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true